spring.application.name=restaurant-management-system

# Database - SQL Server
spring.datasource.url=jdbc:sqlserver://ADMIN-PC\\MSSQLSERVER01:1433;databaseName=restaurant_db;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456s@
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=rms-super-secret-key-for-jwt-must-be-at-least-256-bits-long-ok
jwt.expiration-ms=86400000
